# Generated by Django 4.2 on 2023-05-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Room name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('projector', models.BooleanField(default=False)),
                ('WiFi', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('comment', models.TextField(blank=True)),
                ('email_adress', models.EmailField(max_length=254, verbose_name='Email adress')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationSystem.room')),
            ],
        ),
    ]
