# Generated by Django 4.2 on 2023-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0002_remove_room_id_reservation_user_room_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
