# Generated by Django 4.2 on 2023-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0003_alter_room_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Room ID'),
        ),
    ]
