# Generated by Django 4.2 on 2023-05-02 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0004_alter_room_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.IntegerField(default=0, null=True, unique=True, verbose_name='Room ID'),
        ),
    ]
