# Generated by Django 4.2 on 2023-05-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0005_room_id_alter_room_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomId',
        ),
    ]
