# Generated by Django 4.2 on 2023-05-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0007_remove_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
