# Generated by Django 4.2 on 2023-05-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0010_remove_reservation_is_active_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
