# Generated by Django 4.2 on 2023-05-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0012_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
