# Generated by Django 4.2.1 on 2023-05-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0016_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
