# Generated by Django 4.2.1 on 2023-06-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationSystem', '0018_change_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAndEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('WiFi', models.BooleanField()),
                ('computers', models.BooleanField()),
                ('projector', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationSystem.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationSystem.room'),
        ),
    ]
